### ISSUE TITLE
Does this work on vim?

### ISSUE THREAD

**Issue by morgsmccauley** [garylai/emacs.d#1]
This is a great config, thanks for all your efforts! I was wondering if this works on vim? I like this config but don't want to use emacs.

**Comment by garylai** [comment]
It sure does! To set it up:
```
brew install emacs
echo 'alias vim="emacs"'  >> ~/.zshrc && source ~/.zshrc
```
enjoy! 🎉

**Comment by morgsmccauley** [comment]
Closing as this project is no longer maintained
